const ROLES = Object.freeze({
  EMPLOYEE: 'EMPLOYEE',
  HR_ADMIN: 'HR_ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN'
});

/** Coarse-grained permission matrix — checked by requirePermission() middleware. */
const PERMISSIONS = Object.freeze({
  EMPLOYEE: ['VIEW_OWN_PROFILE', 'VIEW_OWN_ATTENDANCE', 'APPLY_LEAVE', 'VIEW_OWN_PAYSLIP', 'APPROVE_TEAM_LEAVE', 'VIEW_TEAM'],
  HR_ADMIN: ['MANAGE_EMPLOYEES', 'MANAGE_PAYROLL', 'MANAGE_LEAVE', 'MANAGE_ATTENDANCE', 'GENERATE_LETTERS', 'VIEW_REPORTS', 'RESET_EMPLOYEE_PASSWORD', 'MANAGE_TRAINING'],
  SUPER_ADMIN: ['MANAGE_SETTINGS', 'MANAGE_ROLES', 'VIEW_AUDIT_LOG', 'MANAGE_EMPLOYEES', 'MANAGE_PAYROLL', 'MANAGE_LEAVE', 'MANAGE_ATTENDANCE', 'GENERATE_LETTERS', 'VIEW_REPORTS', 'RESET_EMPLOYEE_PASSWORD', 'MANAGE_TRAINING']
});

function hasPermission(role, permission) {
  return !!PERMISSIONS[role] && PERMISSIONS[role].includes(permission);
}

const SYSTEM = Object.freeze({
  APP_NAME: 'MSMG Education Solution',
  EMPLOYEE_CODE_PREFIX: 'EMP',
  EMPLOYEE_CODE_PAD_LENGTH: 6,
  MAX_LOGIN_ATTEMPTS: 5,
  LOCKOUT_MINUTES: 15,
  OTP_EXPIRY_MINUTES: 10,
  BCRYPT_ROUNDS: 10
});

module.exports = { ROLES, PERMISSIONS, hasPermission, SYSTEM };